<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Hato.Modules.Tasks.Application\Hato.Modules.Tasks.Application.csproj" />
    <ProjectReference Include="..\..\Breeding\Hato.Modules.Breeding.Infrastructure\Hato.Modules.Breeding.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Inventory\Hato.Modules.Inventory.Infrastructure\Hato.Modules.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Livestock\Hato.Modules.Livestock.Infrastructure\Hato.Modules.Livestock.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
