// <auto-generated />
using System;
using Hato.Modules.Delivery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hato.Modules.Delivery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hato.Modules.Delivery.Domain.MobileBuildRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("GroupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_request_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("package_name");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("ReleaseTag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("release_tag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TargetApiUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("target_api_url");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.Property<int>("VersionCode")
                        .HasColumnType("integer")
                        .HasColumnName("version_code");

                    b.Property<int?>("WorkflowRunAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_run_attempt");

                    b.Property<long?>("WorkflowRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("p_k_mobile_build_requests");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_mobile_build_requests_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_mobile_build_requests_status");

                    b.HasIndex("Channel", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("i_x_mobile_build_requests_channel_idempotency_key");

                    b.ToTable("mobile_build_requests", "delivery");
                });

            modelBuilder.Entity("Hato.Modules.Delivery.Domain.MobileRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiCompatibility")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("api_compatibility");

                    b.Property<string>("ArtifactFileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("artifact_file_name");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("artifact_sha256");

                    b.Property<long>("ArtifactSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("artifact_size_bytes");

                    b.Property<Guid>("BuildRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_request_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsCurrentStable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current_stable");

                    b.Property<bool>("IsLastGood")
                        .HasColumnType("boolean")
                        .HasColumnName("is_last_good");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("package_name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<string>("ReleaseTag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("release_tag");

                    b.Property<string>("SigningCertificateFingerprint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("signing_certificate_fingerprint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TargetApiUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("target_api_url");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.Property<int>("VersionCode")
                        .HasColumnType("integer")
                        .HasColumnName("version_code");

                    b.Property<string>("WithdrawReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("withdraw_reason");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.Property<Guid?>("WithdrawnBy")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawn_by");

                    b.HasKey("Id")
                        .HasName("p_k_mobile_releases");

                    b.HasIndex("Channel")
                        .IsUnique()
                        .HasDatabaseName("i_x_mobile_releases_channel")
                        .HasFilter("is_current_stable = true");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_mobile_releases_created_at");

                    b.HasIndex("Channel", "Status")
                        .HasDatabaseName("i_x_mobile_releases_channel_status");

                    b.HasIndex("PackageName", "VersionCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_mobile_releases_package_name_version_code");

                    b.ToTable("mobile_releases", "delivery");
                });

            modelBuilder.Entity("Hato.Modules.Delivery.Domain.MobileReleaseTransitionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("p_k_mobile_release_transition_audits");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("i_x_mobile_release_transition_audits_changed_at");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("i_x_mobile_release_transition_audits_release_id");

                    b.ToTable("mobile_release_transition_audits", "delivery");
                });

            modelBuilder.Entity("Hato.Modules.Delivery.Domain.MobileVersionCodeSequence", b =>
                {
                    b.Property<string>("PackageName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("package_name");

                    b.Property<int>("LastVersionCode")
                        .HasColumnType("integer")
                        .HasColumnName("last_version_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PackageName")
                        .HasName("p_k_mobile_version_code_sequences");

                    b.ToTable("mobile_version_code_sequences", "delivery");
                });

            modelBuilder.Entity("Hato.Modules.Delivery.Domain.MobileReleaseTransitionAudit", b =>
                {
                    b.HasOne("Hato.Modules.Delivery.Domain.MobileRelease", null)
                        .WithMany("TransitionAudits")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_mobile_release_transition_audits_mobile_releases_release_id");
                });

            modelBuilder.Entity("Hato.Modules.Delivery.Domain.MobileRelease", b =>
                {
                    b.Navigation("TransitionAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
