// <auto-generated />
using System;
using Hato.Modules.Livestock.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hato.Modules.Livestock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LivestockDbContext))]
    [Migration("20260809165838_AddTreatmentApplicationPlausibilityConfirmed")]
    partial class AddTreatmentApplicationPlausibilityConfirmed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("livestock")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AdministrationRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DefaultUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_unit_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("LabelEs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_es");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_administration_routes");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_administration_routes_is_active");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("i_x_administration_routes_key")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("administration_routes", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<decimal?>("BirthWeightKg")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("birth_weight_kg");

                    b.Property<Guid?>("BirthingId")
                        .HasColumnType("uuid")
                        .HasColumnName("birthing_id");

                    b.Property<Guid?>("BreedId")
                        .HasColumnType("uuid")
                        .HasColumnName("breed_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DisposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disposed_at");

                    b.Property<Guid?>("FatherAnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("father_animal_id");

                    b.Property<Guid?>("FatherStrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("father_straw_id");

                    b.Property<DateTimeOffset?>("LastEditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_at");

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("uuid")
                        .HasColumnName("mother_id");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_animals");

                    b.HasIndex("BreedId")
                        .HasDatabaseName("i_x_animals_breed_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_animals_category_id");

                    b.HasIndex("FatherAnimalId")
                        .HasDatabaseName("i_x_animals_father_animal_id");

                    b.HasIndex("FatherStrawId")
                        .HasDatabaseName("i_x_animals_father_straw_id");

                    b.HasIndex("MotherId")
                        .HasDatabaseName("i_x_animals_mother_id");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("i_x_animals_species_id");

                    b.ToTable("animals", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_animal_categories");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("i_x_animal_categories_species_id");

                    b.ToTable("animal_categories", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AffectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("affected_count");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<Guid?>("AppliedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by_user_id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("CauseId")
                        .HasColumnType("uuid")
                        .HasColumnName("cause_id");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid?>("HealthPlanItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_plan_item_id");

                    b.Property<Guid?>("MigratedToCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("migrated_to_course_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RecordedById")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_id");

                    b.Property<string>("RecordedByLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recorded_by_label");

                    b.Property<Guid?>("RelatedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_event_id");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_animal_events");

                    b.HasIndex("AppliedByUserId")
                        .HasDatabaseName("i_x_animal_events_applied_by_user_id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("i_x_animal_events_batch_id");

                    b.HasIndex("CauseId")
                        .HasDatabaseName("i_x_animal_events_cause_id");

                    b.HasIndex("HealthPlanItemId")
                        .HasDatabaseName("i_x_animal_events_health_plan_item_id");

                    b.HasIndex("MigratedToCourseId")
                        .HasDatabaseName("i_x_animal_events_migrated_to_course_id");

                    b.HasIndex("Reason")
                        .HasDatabaseName("i_x_animal_events_reason");

                    b.HasIndex("RecordedById")
                        .HasDatabaseName("i_x_animal_events_recorded_by_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_animal_events_route_id");

                    b.HasIndex("AnimalId", "OccurredAt")
                        .HasDatabaseName("i_x_animal_events_animal_id_occurred_at");

                    b.HasIndex("GroupId", "OccurredAt")
                        .HasDatabaseName("i_x_animal_events_group_id_occurred_at");

                    b.ToTable("animal_events", "livestock", t =>
                        {
                            t.HasCheckConstraint("CK_AnimalEvent_AffectedCountPositive", "affected_count IS NULL OR affected_count > 0");

                            t.HasCheckConstraint("CK_AnimalEvent_AnimalXorGroup", "(animal_id IS NOT NULL) <> (group_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tracking_mode");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_animal_groups");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("i_x_animal_groups_species_id");

                    b.ToTable("animal_groups", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_animal_identifiers");

                    b.HasIndex("AnimalId", "Type")
                        .IsUnique()
                        .HasDatabaseName("i_x_animal_identifiers_animal_id_type")
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("animal_identifiers", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_breeds");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("i_x_breeds_species_id");

                    b.ToTable("breeds", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.DoseKind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("LabelEs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_es");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_dose_kinds");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_dose_kinds_is_active");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("i_x_dose_kinds_key")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("dose_kinds", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateOnly>("JoinedAt")
                        .HasColumnType("date")
                        .HasColumnName("joined_at");

                    b.Property<DateOnly?>("LeftAt")
                        .HasColumnType("date")
                        .HasColumnName("left_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_group_memberships");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("i_x_group_memberships_animal_id");

                    b.HasIndex("GroupId", "AnimalId", "JoinedAt")
                        .HasDatabaseName("i_x_group_memberships_group_id_animal_id_joined_at");

                    b.ToTable("group_memberships", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.HealthPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_health_plans");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("i_x_health_plans_species_id");

                    b.HasIndex("Name", "SpeciesId")
                        .IsUnique()
                        .HasDatabaseName("i_x_health_plans_name_species_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("health_plans", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.HealthPlanAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("HealthPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_plan_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_health_plan_assignments");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("i_x_health_plan_assignments_animal_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("i_x_health_plan_assignments_group_id");

                    b.HasIndex("HealthPlanId")
                        .HasDatabaseName("i_x_health_plan_assignments_health_plan_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_health_plan_assignments_is_active");

                    b.ToTable("health_plan_assignments", "livestock", t =>
                        {
                            t.HasCheckConstraint("CK_HealthPlanAssignment_AnimalXorGroup", "(animal_id IS NOT NULL) <> (group_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.HealthPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Anchor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("anchor");

                    b.Property<int>("AnchorOffsetDays")
                        .HasColumnType("integer")
                        .HasColumnName("anchor_offset_days");

                    b.Property<Guid?>("AppliesToCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("applies_to_category_id");

                    b.Property<string>("AppliesToSex")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("applies_to_sex");

                    b.Property<int>("ComplianceWindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("compliance_window_days");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("DoseQuantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("dose_quantity");

                    b.Property<Guid?>("DoseUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("dose_unit_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("HealthPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_plan_id");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_health_plan_items");

                    b.HasIndex("AppliesToCategoryId")
                        .HasDatabaseName("i_x_health_plan_items_applies_to_category_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("i_x_health_plan_items_event_type");

                    b.HasIndex("HealthPlanId")
                        .HasDatabaseName("i_x_health_plan_items_health_plan_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_health_plan_items_is_active");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_health_plan_items_route_id");

                    b.ToTable("health_plan_items", "livestock", t =>
                        {
                            t.HasCheckConstraint("CK_HealthPlanItem_OffsetOrRepetition", "anchor_offset_days <> 0 OR repetitions IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.MortalityCause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_mortality_causes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_mortality_causes_name");

                    b.ToTable("mortality_causes", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.PlausibilityRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AbsoluteMax")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("absolute_max");

                    b.Property<decimal?>("AbsoluteMin")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("absolute_min");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Magnitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("magnitude");

                    b.Property<decimal?>("PlausibleMax")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("plausible_max");

                    b.Property<decimal?>("PlausibleMin")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("plausible_min");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_plausibility_ranges");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_plausibility_ranges_category_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_plausibility_ranges_is_active");

                    b.HasIndex("SpeciesId", "CategoryId", "Magnitude")
                        .IsUnique()
                        .HasDatabaseName("i_x_plausibility_ranges_species_id_category_id_magnitude")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("plausibility_ranges", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CohortWindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("cohort_window_days");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int?>("DaysOfLactation")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_lactation");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("GestationDays")
                        .HasColumnType("integer")
                        .HasColumnName("gestation_days");

                    b.Property<bool>("IsMilkable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_milkable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_species");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_species_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("species", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.TreatmentCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DoseFactorAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("dose_factor_amount");

                    b.Property<string>("DoseFactorUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dose_factor_unit");

                    b.Property<Guid>("DoseKindId")
                        .HasColumnType("uuid")
                        .HasColumnName("dose_kind_id");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_treatment_courses");

                    b.HasIndex("DoseKindId")
                        .HasDatabaseName("i_x_treatment_courses_dose_kind_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_treatment_courses_route_id");

                    b.HasIndex("AnimalId", "StartsAt")
                        .HasDatabaseName("i_x_treatment_courses_animal_id_starts_at");

                    b.HasIndex("GroupId", "StartsAt")
                        .HasDatabaseName("i_x_treatment_courses_group_id_starts_at");

                    b.ToTable("treatment_courses", "livestock", t =>
                        {
                            t.HasCheckConstraint("CK_TreatmentCourse_AnimalXorGroup", "(animal_id IS NOT NULL) <> (group_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.TreatmentCourseApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AdministeredDoseAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("administered_dose_amount");

                    b.Property<string>("AdministeredDoseUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("administered_dose_unit");

                    b.Property<int>("ApplicationNo")
                        .HasColumnType("integer")
                        .HasColumnName("application_no");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<decimal?>("CalculatedDoseAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("calculated_dose_amount");

                    b.Property<string>("CalculatedDoseUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("calculated_dose_unit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_estimated");

                    b.Property<bool>("IsPlausibilityConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_plausibility_confirmed");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("TreatmentCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("treatment_course_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_treatment_course_applications");

                    b.HasIndex("AppliedAt")
                        .HasDatabaseName("i_x_treatment_course_applications_applied_at");

                    b.HasIndex("TreatmentCourseId", "ApplicationNo")
                        .IsUnique()
                        .HasDatabaseName("i_x_treatment_course_applications_treatment_course_id_applicati~");

                    b.ToTable("treatment_course_applications", "livestock", t =>
                        {
                            t.HasCheckConstraint("CK_TreatmentCourseApplication_ApplicationNoPositive", "application_no > 0");
                        });
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.TreatmentReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("LabelEs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_es");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_treatment_reasons");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_treatment_reasons_is_active");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("i_x_treatment_reasons_key")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("treatment_reasons", "livestock");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.WithdrawalPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("EndsAt")
                        .HasColumnType("date")
                        .HasColumnName("ends_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateOnly>("StartsAt")
                        .HasColumnType("date")
                        .HasColumnName("starts_at");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target");

                    b.Property<Guid?>("TreatmentCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("treatment_course_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_withdrawal_periods");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_withdrawal_periods_event_id");

                    b.HasIndex("TreatmentCourseId")
                        .HasDatabaseName("i_x_withdrawal_periods_treatment_course_id");

                    b.HasIndex("AnimalId", "EndsAt")
                        .HasDatabaseName("i_x_withdrawal_periods_animal_id_ends_at");

                    b.ToTable("withdrawal_periods", "livestock", t =>
                        {
                            t.HasCheckConstraint("CK_WithdrawalPeriod_EventXorCourse", "(event_id IS NOT NULL) <> (treatment_course_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.Animal", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Breed", null)
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animals_breeds_breed_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animals_animal_categories_category_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("FatherAnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animals_animals_father_animal_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animals_animals_mother_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_animals_species_species_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalCategory", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_animal_categories_species_species_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalEvent", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animal_events_animals_animal_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.MortalityCause", null)
                        .WithMany()
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animal_events_mortality_causes_cause_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animal_events_animal_groups_group_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.HealthPlanItem", null)
                        .WithMany()
                        .HasForeignKey("HealthPlanItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animal_events_health_plan_items_health_plan_item_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("MigratedToCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animal_events_treatment_courses_migrated_to_course_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AdministrationRoute", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animal_events_administration_routes_route_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalGroup", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_animal_groups_species_species_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalIdentifier", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_animal_identifiers_animals_animal_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.Breed", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_breeds_species_species_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.GroupMembership", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_group_memberships_animals_animal_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalGroup", null)
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_group_memberships_animal_groups_group_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.HealthPlan", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_health_plans_species_species_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.HealthPlanAssignment", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_health_plan_assignments_animals_animal_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_health_plan_assignments_animal_groups_group_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.HealthPlan", null)
                        .WithMany()
                        .HasForeignKey("HealthPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_health_plan_assignments_health_plans_health_plan_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.HealthPlanItem", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalCategory", null)
                        .WithMany()
                        .HasForeignKey("AppliesToCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_health_plan_items_animal_categories_applies_to_category_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.HealthPlan", null)
                        .WithMany("Items")
                        .HasForeignKey("HealthPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_health_plan_items_health_plans_health_plan_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AdministrationRoute", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_health_plan_items_administration_routes_route_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.PlausibilityRange", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_plausibility_ranges_animal_categories_category_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_plausibility_ranges_species_species_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.TreatmentCourse", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_treatment_courses_animals_animal_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.DoseKind", null)
                        .WithMany()
                        .HasForeignKey("DoseKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_treatment_courses_dose_kinds_dose_kind_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_treatment_courses_animal_groups_group_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AdministrationRoute", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_treatment_courses_administration_routes_route_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.TreatmentCourseApplication", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.TreatmentCourse", null)
                        .WithMany("Applications")
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_treatment_course_applications_treatment_courses_treatment_c~");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.WithdrawalPeriod", b =>
                {
                    b.HasOne("Hato.Modules.Livestock.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_withdrawal_periods_animals_animal_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.AnimalEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_withdrawal_periods_animal_events_event_id");

                    b.HasOne("Hato.Modules.Livestock.Domain.TreatmentCourse", null)
                        .WithMany()
                        .HasForeignKey("TreatmentCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_withdrawal_periods_treatment_courses_treatment_course_id");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.Animal", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.AnimalGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.HealthPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Hato.Modules.Livestock.Domain.TreatmentCourse", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
